name: Build & Push Local Dev Image

on:
  push:
    branches:
      - dev

env:
  LOCAL_IMAGE_NAME: munjji/jajaja-local

jobs:
  build-and-push-local:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Create resources directory
        run: mkdir -p ./src/main/resources

      - name: Add local application.yml from Secrets
        run: echo "${{ secrets.APPLICATION_LOCAL }}" > ./src/main/resources/application.yml

      - name: Grant permission to gradlew
        run: chmod +x ./gradlew

      - name: Build with Gradle (skip tests)
        run: ./gradlew build -x test

      - name: Build Docker image for local dev
        run: docker build . -t ${{ env.LOCAL_IMAGE_NAME }}:latest

      - name: Docker login
        run: echo "${{ secrets.DOCKER_HUB_TOKEN }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Push local dev Docker image
        run: docker push ${{ env.LOCAL_IMAGE_NAME }}:latest
